# Generated by Django 3.0.8 on 2020-10-20 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_unapproved', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'permissions': (('can_add_post_globally', 'can add post globally'), ('can_delete_post_globally', 'can delete post globally'), ('can_change_post_globally', 'can change post globally'), ('can_view_post_globally', 'can view post globally'), ('can_hide_post_globally', 'can hide post globally'), ('can_approve_post_globally', 'can approve post globally'), ('can_merge_post_globally', 'can merge post globally'), ('can_like_post_globally', 'can like post globally')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PostEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
