# Generated by Django 3.0.8 on 2020-10-20 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_content', models.TextField()),
                ('parsed_content', models.TextField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(choices=[(0, "Don't pin thread"), (1, 'Pin thread within category'), (2, 'Pin thread globally')], default=0)),
                ('is_unapproved', models.BooleanField(db_index=True, default=False)),
                ('is_hidden', models.BooleanField(db_index=True, default=False)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'permissions': (('can_start_thread_globally', 'can start thread globally'), ('can_delete_thread_globally', 'can delete globally'), ('can_change_thread_globally', 'can change globally'), ('can_view_thread_globally', 'can view globally'), ('can_pin_thread_globally', 'can pin thread globally'), ('can_hide_thread_globally', 'can hide globally'), ('can_close_thread_globally', 'can close globally'), ('can_approve_thread_globally', 'can approve globally'), ('can_merge_thread_globally', 'can merge thread globally'), ('can_delete_this_thread', 'can delete this thread'), ('can_change_this_thread', 'can change this thread'), ('can_view_this_thread', 'can view this thread'), ('can_pin_this_thread', 'can pin thread this thread'), ('can_hide_this_thread', 'can hide this thread'), ('can_close_this_thread', 'can close this thread'), ('can_approve_this_thread', 'can approve this thread'), ('can_add_post_in_this_thread', 'can add post of this thread'), ('can_delete_post_in_this_thread', 'can delete post of this thread'), ('can_change_post_in_this_thread', 'can change post of this thread'), ('can_view_post_in_this_thread', 'can view post of this thread'), ('can_hide_post_in_this_thread', 'can hide post of this thread'), ('can_approve_post_in_this_thread', 'can approve post of this thread'), ('can_merge_post_in_this_thread', 'can merge post of this thread'), ('can_like_post_in_this_thread', 'can like post of this thread')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ThreadRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
