# Generated by Django 3.0.8 on 2020-10-22 14:12

import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('threads', '0002_auto_20201020_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='parsed_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='original_content',
        ),
        migrations.AddField(
            model_name='thread',
            name='content_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='title_search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
