# Generated by Django 3.0.8 on 2020-10-22 14:17

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20201022_1412'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_search_vector', 'content_search_vector'], name='threads_thr_title_s_3bb908_gin'),
        ),
    ]
