# Generated by Django 3.0.8 on 2020-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20201022_1417'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER thread_title_update_trigger
            BEFORE INSERT OR UPDATE OF title
            ON threads_thread
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              title_search_vector, 'pg_catalog.english', title);

            CREATE TRIGGER thread_content_update_trigger
            BEFORE INSERT OR UPDATE OF content
            ON threads_thread
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
              content_search_vector, 'pg_catalog.english', content);
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS thread_title_update_trigger ON threads_thread;
            DROP TRIGGER IF EXISTS thread_content_update_trigger ON threads_thread;
            '''
        ),
    ]
