# Generated by Django 3.0.8 on 2020-10-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0005_create_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='last_post_created_on',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
