# Generated by Django 3.0.8 on 2020-10-20 09:15

from django.db import migrations, models

import avatars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(height_field='height', upload_to=avatars.models.upload_to, width_field='width')),
                ('original', models.BooleanField(default=True)),
            ],
        ),
    ]
