# Generated by Django 3.0.8 on 2020-10-20 09:15

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('require_threads_approval', models.BooleanField(default=False)),
                ('require_posts_approval', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'permissions': (('can_view_category', 'can view category'), ('can_delete_category', 'can delete category'), ('can_change_category', 'can change category'), ('can_add_category', 'can add category'), ('can_add_post_in_this_category', 'can add post in this category'), ('can_delete_post_in_this_category', 'can delete post in this category'), ('can_change_post_in_this_category', 'can change post in this category'), ('can_view_post_in_this_category', 'can view post in this category'), ('can_hide_post_in_this_category', 'can hide post in this category'), ('can_approve_post_in_this_category', 'can approve post in this category'), ('can_merge_post_in_this_category', 'can merge post in this category'), ('can_like_post_in_this_category', 'can like post in this category'), ('can_start_thread_in_this_category', 'can start thread in this category'), ('can_delete_thread_in_this_category', 'can delete thread in this category'), ('can_change_thread_in_this_category', 'can change thread in this category'), ('can_view_thread_in_this_category', 'can view thread in this category'), ('can_pin_thread_in_this_category', 'can pin thread in this category'), ('can_hide_thread_in_this_category', 'can hide thread in this category'), ('can_close_thread_in_this_category', 'can close thread in this category'), ('can_approve_thread_in_this_category', 'can approve thread in this category'), ('can_merge_thread_in_this_category', 'can merge thread in this category')),
                'default_permissions': (),
            },
        ),
    ]
